In [2]:
import pandas as pd
df=pd.read_csv("ecommerce_sales_34500.csv")
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4,West,No,139.47,7.88,31.17,60,Female
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6,South,No,24.73,4.60,-2.62,37,Male
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4,North,No,166.80,6.58,13.44,34,Male
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6,South,No,63.67,5.50,2.14,21,Female
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6,East,No,13.88,2.74,1.15,39,Male

In [3]:
df.shape

(34500, 17)

In [4]:
df.columns

Index(['order_id', 'customer_id', 'product_id', 'category', 'price',
       'discount', 'quantity', 'payment_method', 'order_date',
       'delivery_time_days', 'region', 'returned', 'total_amount',
       'shipping_cost', 'profit_margin', 'customer_age', 'customer_gender'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34500 entries, 0 to 34499
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            34500 non-null  object
 1   customer_id         34500 non-null  object
 2   product_id          34500 non-null  object
 3   category            34500 non-null  object
 4   price               34500 non-null  float64
 5   discount            34500 non-null  float64
 6   quantity            34500 non-null  int64
 7   payment_method      34500 non-null  object
 8   order_date          34500 non-null  object
 9   delivery_time_days  34500 non-null  int64
 10  region              34500 non-null  object
 11  returned            34500 non-null  object
 12  total_amount        34500 non-null  float64
 13  shipping_cost       34500 non-null  float64
 14  profit_margin       34500 non-null  float64
 15  customer_age        34500 non-null  int64
 16  customer_gender     34500 non-null  object
dtypes: float64(5), int64(3), object(9)
memory usage: 4.5+ MB

In [6]:
df.isnull().sum()

order_id              0
customer_id           0
product_id            0
category              0
price                 0
discount              0
quantity              0
payment_method        0
order_date            0
delivery_time_days    0
region                0
returned              0
total_amount          0
shipping_cost         0
profit_margin         0
customer_age          0
customer_gender       0
dtype: int64

In [7]:
df.duplicated().sum()

0

In [8]:
df.describe()

,price,discount,quantity,delivery_time_days,total_amount,shipping_cost,profit_margin,customer_age
count,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000,34500.000000
mean,119.391632,0.049291,1.490725,4.814203,170.008494,6.152120,28.116505,43.474377
std,195.620477,0.069894,0.932270,1.242141,357.503014,2.389539,53.352947,14.980682
min,1.010000,0.000000,1.000000,3.000000,0.820000,0.000000,-6.200000,18.000000
25%,16.690000,0.000000,1.000000,4.000000,19.710000,4.420000,1.500000,31.000000
50%,45.660000,0.000000,1.000000,5.000000,56.820000,6.090000,10.550000,43.000000
75%,130.950000,0.100000,2.000000,6.000000,168.530000,7.830000,33.132500,56.000000
max,2930.470000,0.300000,5.000000,13.000000,12931.800000,15.650000,1536.170000,69.000000

In [9]:
df["order_date"].min(),
df["order_date"].max()

'2025-09-11'

In [10]:
df["order_date"].min()

'2023-09-12'

In [10]:
df.dtypes

order_id               object
customer_id            object
product_id             object
category               object
price                 float64
discount              float64
quantity                int64
payment_method         object
order_date             object
delivery_time_days      int64
region                 object
returned               object
total_amount          float64
shipping_cost         float64
profit_margin         float64
customer_age            int64
customer_gender        object
dtype: object

In [11]:
df["order_date"]=pd.to_datetime(df["order_date"])

In [12]:
df.dtypes

order_id                      object
customer_id                   object
product_id                    object
category                      object
price                        float64
discount                     float64
quantity                       int64
payment_method                object
order_date            datetime64[ns]
delivery_time_days             int64
region                        object
returned                      object
total_amount                 float64
shipping_cost                float64
profit_margin                float64
customer_age                   int64
customer_gender               object
dtype: object

In [13]:
df["category"].unique()

array(['Home', 'Grocery', 'Electronics', 'Beauty', 'Fashion', 'Toys',
       'Sports'], dtype=object)

In [16]:
df["payment_method"].unique()

array(['Credit Card', 'UPI', 'COD', 'PayPal', 'Debit Card', 'Wallet'],
      dtype=object)

In [18]:
df["region"].unique()

array(['West', 'South', 'North', 'East', 'Central'], dtype=object)

In [19]:
df["returned"].value_counts()

returned
No     32597
Yes     1903
Name: count, dtype: int64

In [21]:
df["customer_gender"].value_counts()

customer_gender
Female    16818
Male      16310
Other      1372
Name: count, dtype: int64

In [22]:
df["profit_margin"].describe()

count    34500.000000
mean        28.116505
std         53.352947
min         -6.200000
25%          1.500000
50%         10.550000
75%         33.132500
max       1536.170000
Name: profit_margin, dtype: float64

In [23]:
df[df["profit_margin"]==df["profit_margin"].max()]

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
20765,O120765,C16655,P217031,Electronics,2586.36,0.0,5,Debit Card,2024-02-22,5,West,No,12931.8,15.65,1536.17,28,Male

In [24]:
df[df["profit_margin"]>100].shape

(2170, 17)

In [25]:
df["profit_margin"].nlargest(10)

20765    1536.17
7705     1392.96
27798    1341.91
33055    1112.25
6024     1004.97
13451     880.52
17363     765.85
20748     765.28
16950     734.88
24728     727.35
Name: profit_margin, dtype: float64

In [14]:
df_clean=df.copy()

In [15]:
df_clean.shape

(34500, 17)

In [29]:
df_clean["total_amount"].sum()

5865293.050000001

In [30]:
df_clean["order_id"].nunique()

34500

In [31]:
df_clean["total_amount"].mean()

170.00849420289856

In [32]:
df_clean["quantity"].sum()

51430

In [33]:
df_clean.groupby("category")["total_amount"].sum().sort_values(ascending=False)

category
Electronics    3319206.50
Home           1077681.52
Sports          629825.54
Fashion         471545.80
Beauty          153019.38
Toys            132013.80
Grocery          82000.51
Name: total_amount, dtype: float64

In [34]:
df_clean.groupby("region")["total_amount"].sum().sort_values(ascending=False)

region
South      1298096.07
North      1264008.35
West       1186350.50
East       1176334.75
Central     940503.38
Name: total_amount, dtype: float64

In [35]:
df_clean.groupby("payment_method")["total_amount"].sum().sort_values(ascending=False)

payment_method
Credit Card    2056787.40
Debit Card     1460210.97
COD             715571.90
UPI             713642.96
PayPal          576523.32
Wallet          342556.50
Name: total_amount, dtype: float64

In [36]:
df_clean["returned"].value_counts(normalize=True)*100

returned
No     94.484058
Yes     5.515942
Name: proportion, dtype: float64

In [38]:
df_clean.groupby(df_clean["order_date"].dt.to_period("M"))["total_amount"].sum()

order_date
2023-09    151135.60
2023-10    262502.74
2023-11    240286.91
2023-12    255617.03
2024-01    217766.09
2024-02    228013.98
2024-03    248176.28
2024-04    265596.66
2024-05    264875.23
2024-06    234155.38
2024-07    253369.40
2024-08    212613.20
2024-09    218873.90
2024-10    258931.27
2024-11    250572.04
2024-12    278154.19
2025-01    224390.21
2025-02    215338.19
2025-03    239346.81
2025-04    263024.03
2025-05    248527.46
2025-06    248776.28
2025-07    249593.50
2025-08    243808.50
2025-09     91848.17
Freq: M, Name: total_amount, dtype: float64

In [39]:
df_clean.groupby("product_id")["total_amount"].sum().sort_values(ascending=False).head(5)

product_id
P217031    13035.01
P242326    11747.30
P224743    11298.30
P216077     8035.78
P225406     6786.53
Name: total_amount, dtype: float64

In [40]:
df_clean.groupby("category")["total_amount"].mean().sort_values(ascending=False)

category
Electronics    537.088430
Home           196.406328
Sports         151.001088
Fashion         75.399073
Beauty          37.294511
Toys            31.084012
Grocery         20.207124
Name: total_amount, dtype: float64

In [41]:
df_clean.groupby("customer_gender")["total_amount"].sum().sort_values(ascending=False)

customer_gender
Female    2853296.96
Male      2793055.33
Other      218940.76
Name: total_amount, dtype: float64

In [42]:
df_clean.groupby("region")["delivery_time_days"].mean().sort_values(ascending=False)

region
East       5.988847
South      5.005406
West       5.000881
Central    4.006392
North      3.984680
Name: delivery_time_days, dtype: float64

In [43]:
return_rate=(df_clean["returned"]=="Yes").mean()*100
return_rate

5.515942028985507

In [45]:
df_clean.groupby("customer_id")["total_amount"].sum().sort_values(ascending=False).head(5)

customer_id
C16655    13885.10
C13565    11984.28
C15379    11375.58
C17116     7424.34
C15644     7244.07
Name: total_amount, dtype: float64

In [46]:
df_clean.groupby("customer_id")["total_amount"].sum().sort_values(ascending=False).head(5)

customer_id
C16655    13885.10
C13565    11984.28
C15379    11375.58
C17116     7424.34
C15644     7244.07
Name: total_amount, dtype: float64

In [47]:
df_clean[df_clean["returned"]=="Yes"].groupby("category")["order_id"].count().sort_values(ascending=False)

category
Fashion        518
Electronics    451
Home           310
Toys           210
Sports         206
Beauty         155
Grocery         53
Name: order_id, dtype: int64

In [49]:
df_clean.groupby("category")["profit_margin"].mean().sort_values(ascending=False)

category
Electronics    55.723587
Home           47.864717
Sports         38.485114
Fashion        20.597162
Beauty         11.990395
Toys            7.927773
Grocery        -2.264160
Name: profit_margin, dtype: float64

In [50]:
df_clean.groupby("region")["total_amount"].mean().sort_values(ascending=False)

region
West       174.258299
South      171.162456
East       170.384523
Central    166.992788
North      166.931900
Name: total_amount, dtype: float64

In [51]:
df_clean.groupby("customer_gender")["total_amount"].mean().sort_values(ascending=False)

customer_gender
Male      171.248028
Female    169.657329
Other     159.577813
Name: total_amount, dtype: float64

In [52]:
df_clean.groupby(df_clean["order_date"].dt.year)["total_amount"].sum()

order_date
2023     909542.28
2024    2931097.62
2025    2024653.15
Name: total_amount, dtype: float64

In [53]:
df_clean.groupby("category")["quantity"].sum().sort_values(ascending=False)

category
Electronics    9343
Fashion        9148
Home           8229
Toys           6313
Sports         6244
Beauty         6122
Grocery        6031
Name: quantity, dtype: int64

In [54]:
df_clean.groupby("category")["discount"].mean().sort_values(ascending=False)

category
Electronics    0.051068
Sports         0.049916
Beauty         0.049610
Fashion        0.048825
Grocery        0.048817
Home           0.048305
Toys           0.048199
Name: discount, dtype: float64

In [55]:
df_clean.groupby("discount")["total_amount"].mean().sort_index()

discount
0.00    178.942653
0.05    165.480941
0.10    161.617447
0.15    156.427259
0.20    145.689207
0.30    132.530455
Name: total_amount, dtype: float64

In [56]:
df_clean.groupby("category")["delivery_time_days"].mean().sort_values(ascending=False)

category
Fashion        4.866965
Electronics    4.816990
Home           4.808092
Sports         4.801007
Beauty         4.798684
Grocery        4.792262
Toys           4.789263
Name: delivery_time_days, dtype: float64

In [58]:
df_clean.groupby(["payment_method","returned"])["order_id"].count()

payment_method  returned
COD             No           3948
                Yes           212
Credit Card     No          11495
                Yes           675
Debit Card      No           8023
                Yes           482
PayPal          No           3245
                Yes           199
UPI             No           3932
                Yes           224
Wallet          No           1954
                Yes           111
Name: order_id, dtype: int64

In [61]:
df_clean.groupby("payment_method")["total_amount"].mean().sort_values(ascending=False)

payment_method
COD            172.012476
UPI            171.713898
Debit Card     171.688533
Credit Card    169.004717
PayPal         167.399338
Wallet         165.886925
Name: total_amount, dtype: float64

In [63]:
df_clean.groupby("category")["profit_margin"].sum().sort_values(ascending=False)

category
Electronics    344371.77
Home           262633.70
Sports         160521.41
Fashion        128814.65
Beauty          49196.59
Toys            33669.25
Grocery         -9187.96
Name: profit_margin, dtype: float64

In [64]:
df_clean.groupby("region")["profit_margin"].mean().sort_values(ascending=False)

region
West       28.993204
East       28.249600
Central    28.058184
South      27.832433
North      27.534810
Name: profit_margin, dtype: float64

In [9]:
df_clean.groupby("region")["shipping_cost"].sum().sort_values(ascending=False)

region
South      46734.38
North      46260.22
East       42802.62
West       41982.52
Central    34468.39
Name: shipping_cost, dtype: float64

In [10]:
df_clean.groupby("quantity")["price"].mean()

quantity
1    119.048121
2    116.222439
3    129.174008
4    120.425908
5    118.429509
Name: price, dtype: float64

In [13]:
df_clean.groupby("product_id")["quantity"].sum().sort_values(ascending=False).head(5)

product_id
P222065    14
P211187    13
P247881    13
P234626    12
P242018    11
Name: quantity, dtype: int64

In [14]:
df_clean.groupby("category")["customer_age"].mean().sort_values(ascending=False)

category
Grocery        44.018236
Toys           43.884154
Home           43.577365
Beauty         43.529856
Fashion        43.526383
Electronics    43.060680
Sports         42.872932
Name: customer_age, dtype: float64

In [17]:
df_clean.groupby("category")["shipping_cost"].mean().sort_values(ascending=False)

category
Electronics    8.727034
Home           7.129098
Sports         6.815052
Fashion        5.792328
Beauty         4.792237
Toys           4.505846
Grocery        3.880734
Name: shipping_cost, dtype: float64

In [19]:
df_clean.groupby(["region","customer_gender"])["total_amount"].mean()

region   customer_gender
Central  Female             164.614189
         Male               171.798952
         Other              135.234348
East     Female             166.718028
         Male               174.118361
         Other              171.421683
North    Female             170.341388
         Male               163.302570
         Other              169.522753
South    Female             173.571688
         Male               169.662847
         Other              159.313441
West     Female             171.587163
         Male               178.655059
         Other              152.726851
Name: total_amount, dtype: float64

In [20]:
df_clean["customer_id"].nunique()

7903

In [21]:
df_clean.groupby("customer_id")["order_id"].count().sort_values(ascending=False).head(5)

customer_id
C11573    13
C16704    13
C14228    12
C14675    12
C17595    12
Name: order_id, dtype: int64

In [22]:
df_clean["quantity"].mean()

1.4907246376811594

In [27]:
df_clean["order_date"]=pd.to_datetime(df_clean["order_date"])
df_clean.groupby(df_clean["order_date"].dt.year)["quantity"].sum()

order_date
2023     7709
2024    25616
2025    18105
Name: quantity, dtype: int64

In [28]:
df_clean.groupby("category")["order_id"].count().sort_values(ascending=False)

category
Fashion        6254
Electronics    6180
Home           5487
Toys           4247
Sports         4171
Beauty         4103
Grocery        4058
Name: order_id, dtype: int64

In [29]:
df_clean.groupby("region")["order_id"].count().sort_values(ascending=False)

region
South      7584
North      7572
East       6904
West       6808
Central    5632
Name: order_id, dtype: int64

In [30]:
df_clean.groupby("payment_method")["order_id"].count().sort_values(ascending=False)

payment_method
Credit Card    12170
Debit Card      8505
COD             4160
UPI             4156
PayPal          3444
Wallet          2065
Name: order_id, dtype: int64

In [31]:
df_clean[df_clean["profit_margin"]>100].shape

(2170, 17)

In [32]:
df_clean["profit_margin"].nlargest(10)

20765    1536.17
7705     1392.96
27798    1341.91
33055    1112.25
6024     1004.97
13451     880.52
17363     765.85
20748     765.28
16950     734.88
24728     727.35
Name: profit_margin, dtype: float64

In [33]:
df_clean.to_csv("ecommerce_sales_cleaned.csv",index=False)

In [34]:
df_clean.shape

(34500, 17)

In [35]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34500 entries, 0 to 34499
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            34500 non-null  object
 1   customer_id         34500 non-null  object
 2   product_id          34500 non-null  object
 3   category            34500 non-null  object
 4   price               34500 non-null  float64
 5   discount            34500 non-null  float64
 6   quantity            34500 non-null  int64
 7   payment_method      34500 non-null  object
 8   order_date          34500 non-null  datetime64[ns]
 9   delivery_time_days  34500 non-null  int64
 10  region              34500 non-null  object
 11  returned            34500 non-null  object
 12  total_amount        34500 non-null  float64
 13  shipping_cost       34500 non-null  float64
 14  profit_margin       34500 non-null  float64
 15  customer_age        34500 non-null  int64
 16  customer_gender     34500 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(3), object(8)
memory usage: 4.5+ MB